### ISSUE TITLE
Rough planned release date?

### ISSUE THREAD

**Issue by dleuthe** [exasol/glue-connector#32]
Dear morazow,
dear kaklakariada,

during my research I just found this repo regard a connector for Glue Studio. I think it is great that you do this and appreciate the work very much.
I would be very interested to know, if you already have an approximate release date or a rough time estimate?

Thanks you very much and best regards :)

**Comment by morazow** [comment]
Hello @dleuthe,

Thanks for the interest!

We are planning to release it to Glue Studio Marketplace by the end of June. 

Before that we may also do a release with developer guide so that users could set this as custom connector on the Glue studio.

Best

**Comment by morazow** [comment]
Hello @dleuthe,

I wanted to inform you that you should be already able to use the connector from the AWS Glue Studio, please also checkout our user guide for more information.

![Screenshot from 2022-08-05 09-30-21](https://user-images.githubusercontent.com/916295/183026463-aafbf0f0-a86a-4518-b6be-4e408fc35e66.png)



Thanks again for the interest!
